stages:
  - deploy

deploy:
  stage: deploy
  image: kroniak/ssh-client

  before_script:
    - mkdir -p ~/.ssh
    - echo "$MASTER_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - echo "$(cat ~/.ssh/id_rsa)"
    - chmod 700 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts

  script:
    - ssh -o StrictHostKeyChecking=no "${MASTER_SSH_USER}@${MASTER_HOST}" "cd /var/www/mc-client && sudo docker-compose stop && sudo git pull && sudo npm run build  && sudo docker-compose build && sudo docker-compose up -d"