language: node_js
node_js:
    - node
branches:
    only:
        - master
deploy:
    provider: heroku
    api_key:
        secure: uc3Ill5QTNXUY8ftZM7MGvLDHsUlhg+wJMWzD4kuX0wOeULeH/AbPufECqG6sXTmhihh5LIZQwt1Aab4V/56VlhDhdMhvlgSln3wQjjN2s90SZgmU64HLEEg2YehTU/PpZt3NXeuOoUnt9yt6b8LEIySRMU0lDqbF6FpWresHgC1RkjFdY6EwAwqLlTg6RLtLYLsT/k010NoDsPzjaoFiHn7381L3Ip8QNzJHjtykkxfzJWOxrwykHZkMvP3z+DCvhhly8GFWqqsVCRXL8of8fgqLUs4lZQ56n4lkk+WiOJ8xmMVl3acdbk0rGJFSvTjG+Z2s1k3IiIoVdCes8hnxkhZQaMs3l47eTXLB1NvZibq5yhrliRgORz7tfri4iaa08xpGWKTjJU0tSTbVxDIm9SFdHVjabrgYq9qxgq6aAR7BJ6Zp34gwGiVXblUopU8JzQRQjaC6I00V7T57rw05aE1WPF2y7/dLrnBeiOIF0OMBBbuRa6M7XULSeXGuIiSO8XOkpWitEBzDli5gxcSC2HLLZcQO2ZS+pOSkcUC82T8y+bcKEqgmyJjxE2+b4aO5KnY1mt0QVlXJJvp/3pnMojC7C3oAbk0kbuROK69RvSGhbz1YG+BmQS0GDORFbKRXPkfnH4eLWXGFv0kprRrDXRLTgCBy4hjX+0imyT7WbE=
    app: medicine-consultation-client
    on:
        repo: zotovY/medicine-consultation-client
    skip_cleanup: "true"
