language: node_js
node_js:
    - node
branches:
    only:
        - master
deploy:
    provider: heroku
    api_key:
        secure: pkQyRgRk3vLpvi4CfUvynqHqFi7XeuS7EhAYwigl8H+T3/DM4ON+biBXdEt8gKAj0jNAt8t6L8bUlXougJsLG0R4NDGX0UKhlPND8RmR51XKPLO5UBq69y0i5Fs8ylOenhOAY2mCJaHt+wGDdpu05fWQzAXZ8vhl4iD7C5Vp6Qwz4JlOOaM3gHUevUMln2ScIe8wZIU24vGmJNH3eqrXe4WVdUkID104UiS5UcEPBra6sdsl7YD+hCMlTB79TG5vYvnYUEaFhuNBVX1VPiqgI5xioiVf7xBalK/A6uvgZCin0Kw7zD2SAmnggNxIY7VPSsteoyxiSIiaJojK3PH2ATuYeuMA3BrZYJXGPC4iqCcF78Fvv65uRoZf+iP6paosAA/wE3f0/2G2OGmLs8PfRl61csPCvlg4AF9FRDL3wNivbO2j2GuT0q0KUO0mZ9FUPRWrmTovTvKGeq7zNmWsm4+UKLnmx/UwU2ZFrnWvIwuqkz71ARUd3Em97sELuDtb4SxhdnkAqYRbCP/RFiudzWxfkAe3yKcsuIxIZ6eCQVpVHjiR83FFe2NMuhIOY1OOYGz2QEyauDeCr6JOFQiKVOmzeUW4qJBo5oO8PCUofrLNFKiXMvVVNOnuvMiFLm3ZRQZhmAFiUIzSUOqEFtkV+Lf3Ae+jDSxWon4wyax1S7g=
    app: medicine-consultation-client
    on:
        repo: zotovY/medicine-consultation-client
    skip_cleanup: "true"
