language: node_js
node_js:
- node
branches:
  only:
  - master
deploy:
  provider: heroku
  app: medicine-consultation-client
  api_key:
    secure: mYVSLSmT/NoMkIlwWjLeuUiMyUjXfeBAJ7hE5XUrVJuA9Um1Kuk9P2KhH7np0xNIGvj6OvxNdHjYtdhmm+oCcN9QeS2Ucz9HKevqCjUAFN6BSffEQA5iC69DXozvbREEILTWtESeMi6HbwzVBB/2waYnFa01nAa6ALi6Eok3EmYBEbPpi0tS4mqY/IMVjRRVoB7p4PysnQq2xhQrM+VghWBRdzgqr+sYVMa/XAp9Hk6eTCwMeHkeZA2p6xU2MIUdbNdiUW9E7Xm9Kl4dmHt8lk1/aEpAlVaAwq8s79C+Vvn+fYtEu4LFMVk+Mg5yMthPP5SiK/h9iZszZ16qFkLYjp7+2zT+KntKYHxFHgCq1LcmhNhm6jsgcXBkBsuL5IT0ReM9gnBBGEFHgfR/0ps4po+XMsA2Q/9Ze+6ZJKBA0WKzdqmNtXuv3hqU3h0yl4tCLL7Xg6UxfunjDDLpDMnz/hsuagxruvXy2neF2ogoHttCEnkP93mqtkFqEWk3A8nwrl4vtKK7Lq5iZxA0aAI5wbKYUO6fjuOONJpXYIt2mOmvzaek9thM5Ed/yCRKi2Nvwp2pLYkdrq/RFbJliwllQV9sGr2kvY/nTnDfEUGYcU4DCgbSlPO0vG3L1SpJz1ckqmvmmSDbJy5TmA9vTKrpImKHNgn+8DhmaYo+84weSoc=
