language: node_js
node_js:
    - node
branches:
    only:
        - master
deploy:
    provider: heroku
    app: medicine-consultation-client
    api_key:
        secure: PBW+n1oKqAmaBy69mUGv++8/JXogMAyv5WzPhk6hCrQ3HpZRN9h93nPfSQXB7WT9q7eI/EDjammwxLbEBxvZ+R4Ecoo+HCZnCgiIZc+FsIW9db2nbHBRQfm2DFhr+TNfsR6geKWRXiPkKuOvUUfYnzE7q34gM4ZP7vFdh9N32mI0IsOD69H4QVvuCfIaVFqqlzg62MxZFfeHdWtXzbtfikMPCcKeXE2B9o1fQTc3pzxBfrDxYE3Wkj1i3psxi+1ow2KR4eak5mqMBU8/KOSjRKoIp9Nl6oC3dCEXLq32FGJZ1cvtcVJiG+ax1mD2W7Xhw6n8xTLoZppAuYKPyE1MqDxECUkbhBvPsvlaK2QiooThNkm+h3ukbqRBD/m5vcqjZ2K9ufbjvq3mcXrnnigwC1CmMERPg9tmM3dPmE2UXF6ILo/tD+x9/ij5sqrF9n61H3jJnmHsC8jp8qIjcb7qWXmdkhYl8VOI3nBkI4ebC7Q84dL/DsYj6btjkRVO1E3Q0LQh9dnMGvTDn1fw4A8/2XoXrkp4xgcFH5WYCpb+MrvZpnp4hudcsa58lQlu6S71oRpP47KioGNilQC4qQWgCwj6LHm1pIgUK7flLWZOujxlQr++r8rjgYhNGgEunnlE3nISYeAM6VQrroZvj/Wrq+WjTyJ2Xq19Xjj5ZFmOROc=
