language: node_js
node_js:
- node
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: q8PjGFSOCyewOvg1KE2HiWWCdurJ7WQAOi3hjNR0UCnmSUZUU6aiwj8nWpVCNCYZKMzjx+Ik6E+pSVIshE5Ud5jxsWnxUGtAh0lns2y70GQtZ3kznhFDBVg6CQnwr93oL85uWzRT3Ddg+r3aKqqePgdkF8aEpRpWoZ3yhjKegPhOBU1/E+PZdvzgw8gyEId/uhZcHv2TUkRbfjyqha3tNUCsPjBfrc2rKWJpsJ0/2OwwH9jiFMXizMcTquBS/h/hEfuRXhChVHZcsJ0IdMALXUF8KqGC15Ynuzsay70LMtfwBWFHzpKbElJF6rZvN1BBJpLRYsuMYGzKhASYqAmvaCR3EKJ3WlQDIymQ+Wq7HsKM83YQSY8j0kAsbe5nHBZKaEWDT4BG5N1SYzGaaGy7R0oKgjSdWgYAJG0nYJ0e/gYBAPnhlGoz96Y6Hmx///rKI6zfp8N2O9yG4QlxC5AKFno4w2MZ41oxTA1r+2G1wXt+r73uz1NzS5qQNHZIH9vbwWfLVLxTYgDNx81Yb57IxfeSQo0GAipJu4uwAss+zM2NZTIZgdkrymc92EUrOkJDEw3Zoh7BNoDWB8twI98whyR4PvVPjp2CDAtMnOauz8X3D9CzNxoPirU4QeJgz36jlnTz3rcnfzPtAeP0Dgsk/Zy7krVBvJatjrnubp/1jk8=
  app: medicine-consultation-client
  on:
    repo: zotovY/medicine-consultation-client
  skip_cleanup: 'true'
